# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21


      - name: Install dependencies
        run: |
          go mod download

      - name: Run Go Vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...

  publish:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ANBURBAEVA }}
          password: ${{ secrets.dckr_pat_yLdyVuGbMtBAnFHDwbQbH0wB9hw }}

      - name: Build and push Docker image
        run: |
          docker build -t Final-main1:latest .
          docker push ralphiko/Final-main1:latest