

name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21


      - name: Install dependencies
        run: |
          go mod download

      - name: Run Go Vet
        run: go vet ./...

      - name: Run tests
        run: go test ./...

  publish:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.dckr_pat_yLdyVuGbMtBAnFHDwbQbH0wB9hw }}" | docker login -u "${{ secrets.anburbaeva }}" --password-stdin





      - name: Build and push Docker image
        run: |
          docker build -t token:latest .
          docker push anburbaeva/token:latest